import { FABRICS, COLORS } from "../data/products";
export function Filters({ activeCategory, setActiveCategory, selectedFabrics, setSelectedFabrics, selectedColors, setSelectedColors, priceMax, setPriceMax, setSearch, search }: any){
  return (
    <aside className="lg:w-[260px] shrink-0">
      <div className="lg:sticky lg:top-[96px] space-y-6">
        <div className="flex items-center justify-between"><h3 className="font-serif text-[18px]">Refine</h3><button onClick={()=>{setSelectedFabrics([]); setSelectedColors([]); setPriceMax(22000); setSearch(""); setActiveCategory("All");}} className="font-sans text-[11px] tracking-[0.08em] uppercase text-[#8B7355] hover:text-[#4A0E0E]">Clear all</button></div>
        <div className="space-y-3"><div className="font-sans text-[11px] tracking-[0.15em] uppercase text-[#8B7355]">Category</div><div className="flex flex-wrap gap-2">{["All","Sarees","Suits","Kurtis","New Arrivals"].map(c=>(<button key={c} onClick={()=>setActiveCategory(c)} className={`px-3.5 py-2 rounded-full border text-[12px] font-sans tracking-wide transition ${activeCategory===c?"bg-[#4A0E0E] text-white border-[#4A0E0E]":"bg-white border-[#E9DDD1] hover:border-[#C9A86A]"}`}>{c}</button>))}</div></div>
        <div className="bg-white rounded-[16px] border border-[#E9DDD1] p-5"><div className="font-sans text-[11px] tracking-[0.15em] uppercase text-[#8B7355] mb-3">Fabric</div><div className="space-y-2.5">{FABRICS.map((f:string)=>(<label key={f} className="flex items-center gap-2.5 cursor-pointer group"><input type="checkbox" checked={selectedFabrics.includes(f)} onChange={e=>{ if(e.target.checked) setSelectedFabrics([...selectedFabrics,f]); else setSelectedFabrics(selectedFabrics.filter((x:string)=>x!==f));}} className="w-4 h-4 rounded border-[#E9DDD1] text-[#4A0E0E] focus:ring-[#C9A86A]/30"/><span className="font-sans text-[13px] group-hover:text-[#4A0E0E]">{f}</span></label>))}</div></div>
        <div className="bg-white rounded-[16px] border border-[#E9DDD1] p-5"><div className="font-sans text-[11px] tracking-[0.15em] uppercase text-[#8B7355] mb-3">Color</div><div className="flex flex-wrap gap-2.5">{COLORS.map((c:any)=>(<button key={c.name} onClick={()=>{ if(selectedColors.includes(c.name)) setSelectedColors(selectedColors.filter((x:string)=>x!==c.name)); else setSelectedColors([...selectedColors,c.name]);}} className={`w-8 h-8 rounded-full border-2 flex items-center justify-center transition ${selectedColors.includes(c.name)?"border-[#4A0E0E] ring-2 ring-[#C9A86A]/30":"border-white shadow-sm"}`} style={{background:c.hex}} title={c.name}/>))}</div></div>
        <div className="bg-white rounded-[16px] border border-[#E9DDD1] p-5"><div className="font-sans text-[11px] tracking-[0.15em] uppercase text-[#8B7355] mb-3">Price: up to Rs {priceMax.toLocaleString("en-IN")}</div><input type="range" min={2000} max={22000} step={500} value={priceMax} onChange={e=>setPriceMax(Number(e.target.value))} className="w-full accent-[#4A0E0E]"/><div className="flex justify-between font-sans text-[11px] text-[#8B7355] mt-1"><span>Rs 2,000</span><span>Rs 22,000</span></div></div>
      </div>
    </aside>
  )
}
