import { X, Star, ShoppingBag, MessageCircle } from "lucide-react";
export function QuickView({ product, onClose, onAdd, whatsappLink }: any){
  if(!product) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div onClick={onClose} className="absolute inset-0 bg-[#2B1A0E]/40 backdrop-blur-sm"/>
      <div className="relative w-full max-w-[880px] max-h-[90vh] overflow-hidden bg-[#FFFBF7] rounded-[24px] border border-[#E9DDD1] shadow-[0_30px_80px_rgba(0,0,0,0.2)] flex flex-col md:flex-row">
        <button onClick={onClose} className="absolute top-4 right-4 z-10 w-9 h-9 rounded-full bg-white border border-[#E9DDD1] flex items-center justify-center shadow-sm"><X className="w-4 h-4"/></button>
        <div className={`md:w-[46%] aspect-[4/5] md:aspect-auto md:min-h-[520px] bg-gradient-to-br ${product.gradient} p-5 md:p-6 relative overflow-hidden`}><img src="/assets/navbar-bg.png" alt={product.name} className="absolute inset-0 h-full w-full object-cover opacity-100 scale-110" /><div className={`absolute inset-0 bg-gradient-to-br ${product.gradient} opacity-35 mix-blend-multiply`}/><div className="absolute inset-0 bg-white/5 mix-blend-screen"/><div className="relative w-full h-full rounded-[18px] bg-white/42 backdrop-blur-[1px] border border-white shadow-sm p-4 flex flex-col justify-between"><div><div className="inline-flex px-2.5 py-1 rounded-full bg-[#FFFBF7] border border-[#E9DDD1] font-sans text-[10px] uppercase tracking-wide">{product.fabric} • {product.texture}</div><div className="mt-6 font-serif text-[26px] leading-[1.1] text-[#2B1A0E]">{product.name}</div></div><div className="space-y-3"><div className="w-full h-px bg-[#E9DDD1]"/><div className="grid grid-cols-2 gap-3 font-sans text-[11px]"><div><div className="tracking-[0.12em] uppercase text-[#8B7355]">Blouse</div><div className="mt-1 text-[#2B1A0E] leading-snug">{product.blouse}</div></div><div><div className="tracking-[0.12em] uppercase text-[#8B7355]">Color</div><div className="mt-1 flex items-center gap-1.5"><span className="w-3 h-3 rounded-full border border-white shadow" style={{background:product.colorHex}}/>{product.color}</div></div></div></div></div></div>
        <div className="flex-1 p-6 md:p-8 overflow-y-auto"><div className="flex items-center gap-2"><div className="flex">{Array.from({length:5}).map((_,i)=><Star key={i} className={`w-4 h-4 ${i < Math.floor(product.rating)? "fill-[#C9A86A] text-[#C9A86A]":"text-[#E9DDD1]"}`}/>)}</div><span className="font-sans text-[12px] text-[#8B7355]">{product.rating} ({product.reviews} reviews)</span></div><h3 className="font-serif text-[24px] leading-[1.15] mt-3">{product.name}</h3><div className="mt-3 flex items-baseline gap-3"><span className="font-serif text-[22px] font-semibold text-[#4A0E0E]">Rs {product.price.toLocaleString("en-IN")}</span>{product.originalPrice && <span className="font-sans text-[13px] line-through text-[#8B7355]">Rs {product.originalPrice.toLocaleString("en-IN")}</span>}</div><p className="font-sans text-[13px] leading-[1.7] text-[#5A4633] mt-4">{product.description}</p><div className="mt-6 grid gap-3">{[{title:"Fabric Details",text:`${product.fabric} • ${product.texture} • 60gm base where applicable`},{title:"2-Taar Explanation",text:"Two delicate threads create shadow work. Front shows tender jaali, back holds the secret stitch. Takes 2x longer than single-taar."},{title:"Care Instructions",text:"Dry clean only. Store folded in muslin with neem leaves. Avoid direct deodorant spray. Steam on low."}].map(b=>(<div key={b.title} className="bg-white border border-[#E9DDD1] rounded-[12px] p-4"><div className="font-sans text-[11px] tracking-[0.15em] uppercase text-[#8B7355]">{b.title}</div><div className="font-sans text-[12px] leading-[1.6] text-[#2B1A0E] mt-1.5">{b.text}</div></div>))}</div><div className="mt-6 flex gap-3"><button onClick={()=>{onAdd(product); onClose();}} className="flex-1 h-11 rounded-full bg-[#4A0E0E] text-white font-sans text-[12px] tracking-[0.08em] uppercase flex items-center justify-center gap-2 hover:bg-[#5A1A1A] transition"><ShoppingBag className="w-4 h-4"/> Add to Bag • Rs {product.price.toLocaleString("en-IN")}</button><a href={whatsappLink(product)} target="_blank" className="w-11 h-11 rounded-full bg-white border border-[#E9DDD1] flex items-center justify-center hover:border-[#C9A86A] transition"><MessageCircle className="w-5 h-5 text-[#8B7355]"/></a></div><div className="mt-4 font-sans text-[11px] text-[#8B7355] text-center">Order via WhatsApp: 9768956956 • Worldwide shipping • No COD</div></div>
      </div>
    </div>
  )
}
